(function () {
  const app = (window.SortingApp = window.SortingApp || {});
  app.elements = {
    dataInput: document.querySelector("#dataInput"),
    validationMessage: document.querySelector("#validationMessage"),
    sampleButton: document.querySelector("#sampleButton"),
    clearInputButton: document.querySelector("#clearInputButton"),
    algorithmSelect: document.querySelector("#algorithmSelect"),
    speedRange: document.querySelector("#speedRange"),
    speedLabel: document.querySelector("#speedLabel"),
    startButton: document.querySelector("#startButton"),
    stepButton: document.querySelector("#stepButton"),
    autoButton: document.querySelector("#autoButton"),
    stopButton: document.querySelector("#stopButton"),
    resetButton: document.querySelector("#resetButton"),
    heroAlgorithm: document.querySelector("#heroAlgorithm"),
    runStatus: document.querySelector("#runStatus"),
    roundCount: document.querySelector("#roundCount"),
    comparisonCount: document.querySelector("#comparisonCount"),
    swapCount: document.querySelector("#swapCount"),
    beforeArray: document.querySelector("#beforeArray"),
    afterArray: document.querySelector("#afterArray"),
    currentStepMessage: document.querySelector("#currentStepMessage"),
    barsContainer: document.querySelector("#barsContainer"),
    stepsTableBody: document.querySelector("#stepsTableBody"),
    algorithmTitle: document.querySelector("#algorithmTitle"),
    algorithmPrinciple: document.querySelector("#algorithmPrinciple"),
    algorithmIdea: document.querySelector("#algorithmIdea"),
    bestCase: document.querySelector("#bestCase"),
    averageCase: document.querySelector("#averageCase"),
    worstCase: document.querySelector("#worstCase"),
    spaceCase: document.querySelector("#spaceCase"),
    algorithmHighlights: document.querySelector("#algorithmHighlights"),
    heapTreeSection: document.querySelector("#heapTreeSection"),
    heapTreeMessage: document.querySelector("#heapTreeMessage"),
    heapTreeContainer: document.querySelector("#heapTreeContainer"),
    heapSortedTail: document.querySelector("#heapSortedTail"),
    processGalleryMessage: document.querySelector("#processGalleryMessage"),
    processGallery: document.querySelector("#processGallery"),
  };
})();
